# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='披萨名称')),
            ],
            options={
                'verbose_name': '披萨',
                'verbose_name_plural': '披萨',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='配料')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza', verbose_name='披萨')),
            ],
            options={
                'verbose_name': '配料',
                'verbose_name_plural': '配料',
            },
        ),
    ]
