# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 05:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
    ]
